# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1394, 716)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1394, 716))
        MainWindow.setMaximumSize(QtCore.QSize(1394, 716))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 1451, 711))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setAccessibleName("")
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"  border: 1px solid lightgray;\n"
"  top:-1px; \n"
"  background: rgb(245, 245, 245);; \n"
"} \n"
"\n"
"QTabBar::tab {\n"
"  background: rgb(230, 230, 230); \n"
"  border: 1px solid lightgray; \n"
" padding: 30px 15px;\n"
"  border-radius: 4px;\n"
"min-width: 150px;\n"
"\n"
"\n"
"  font: 900 12pt \"Segoe UI Black\";\n"
"} \n"
"\n"
"QTabBar::tab:selected { \n"
"  background: rgb(245, 245, 245); \n"
"  margin-bottom: -1px; \n"
"}\n"
"")
        self.tabWidget.setIconSize(QtCore.QSize(30, 30))
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName("tabWidget")
        self.FilterTab = QtWidgets.QWidget()
        self.FilterTab.setObjectName("FilterTab")
        self.ImagesFrame = QtWidgets.QFrame(self.FilterTab)
        self.ImagesFrame.setGeometry(QtCore.QRect(280, 50, 1121, 571))
        self.ImagesFrame.setStyleSheet("background-color: transparent;\n"
"border-radius:5px;")
        self.ImagesFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ImagesFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ImagesFrame.setObjectName("ImagesFrame")
        self.outputImageLabel = QtWidgets.QLabel(self.ImagesFrame)
        self.outputImageLabel.setGeometry(QtCore.QRect(750, 10, 191, 31))
        self.outputImageLabel.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.outputImageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.outputImageLabel.setObjectName("outputImageLabel")
        self.inputImageLabel = QtWidgets.QLabel(self.ImagesFrame)
        self.inputImageLabel.setGeometry(QtCore.QRect(170, 10, 191, 31))
        self.inputImageLabel.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.inputImageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.inputImageLabel.setObjectName("inputImageLabel")
        self.filter_inputImage = QtWidgets.QLabel(self.ImagesFrame)
        self.filter_inputImage.setGeometry(QtCore.QRect(20, 50, 512, 512))
        self.filter_inputImage.setStyleSheet("border: 4px solid black;\n"
"")
        self.filter_inputImage.setText("")
        self.filter_inputImage.setScaledContents(True)
        self.filter_inputImage.setAlignment(QtCore.Qt.AlignCenter)
        self.filter_inputImage.setObjectName("filter_inputImage")
        self.filter_outputImage = QtWidgets.QLabel(self.ImagesFrame)
        self.filter_outputImage.setGeometry(QtCore.QRect(580, 50, 512, 512))
        self.filter_outputImage.setStyleSheet("border: 4px solid black;\n"
"")
        self.filter_outputImage.setText("")
        self.filter_outputImage.setScaledContents(True)
        self.filter_outputImage.setAlignment(QtCore.Qt.AlignCenter)
        self.filter_outputImage.setObjectName("filter_outputImage")
        self.RefreshButton = QtWidgets.QPushButton(self.FilterTab)
        self.RefreshButton.setGeometry(QtCore.QRect(1250, 20, 121, 51))
        self.RefreshButton.setStyleSheet("QPushButton{\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/convert_color_to_gray.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RefreshButton.setIcon(icon)
        self.RefreshButton.setIconSize(QtCore.QSize(50, 50))
        self.RefreshButton.setObjectName("RefreshButton")
        self.Filtering = QtWidgets.QWidget(self.FilterTab)
        self.Filtering.setGeometry(QtCore.QRect(30, 130, 241, 221))
        self.Filtering.setStyleSheet("QWidget{\n"
"border: 2px solid;\n"
"border-radius: 5px;\n"
"}")
        self.Filtering.setObjectName("Filtering")
        self.AverageFilterButton = QtWidgets.QPushButton(self.Filtering)
        self.AverageFilterButton.setGeometry(QtCore.QRect(10, 90, 221, 51))
        self.AverageFilterButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.AverageFilterButton.setObjectName("AverageFilterButton")
        self.MedianFilterButton = QtWidgets.QPushButton(self.Filtering)
        self.MedianFilterButton.setGeometry(QtCore.QRect(10, 30, 221, 51))
        self.MedianFilterButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.MedianFilterButton.setObjectName("MedianFilterButton")
        self.GaussianFilterButton = QtWidgets.QPushButton(self.Filtering)
        self.GaussianFilterButton.setGeometry(QtCore.QRect(10, 150, 221, 51))
        self.GaussianFilterButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.GaussianFilterButton.setObjectName("GaussianFilterButton")
        self.Radio3x3Kernal = QtWidgets.QRadioButton(self.Filtering)
        self.Radio3x3Kernal.setGeometry(QtCore.QRect(60, 5, 50, 20))
        self.Radio3x3Kernal.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 15px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.Radio3x3Kernal.setChecked(True)
        self.Radio3x3Kernal.setObjectName("Radio3x3Kernal")
        self.Radio5x5Kernal = QtWidgets.QRadioButton(self.Filtering)
        self.Radio5x5Kernal.setGeometry(QtCore.QRect(130, 5, 50, 20))
        self.Radio5x5Kernal.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 15px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.Radio5x5Kernal.setObjectName("Radio5x5Kernal")
        self.Noise = QtWidgets.QWidget(self.FilterTab)
        self.Noise.setGeometry(QtCore.QRect(30, 400, 241, 211))
        self.Noise.setStyleSheet("border: 2px solid;\n"
"border-radius: 5px;")
        self.Noise.setObjectName("Noise")
        self.UniformNoiseButton = QtWidgets.QPushButton(self.Noise)
        self.UniformNoiseButton.setGeometry(QtCore.QRect(10, 80, 221, 51))
        self.UniformNoiseButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.UniformNoiseButton.setObjectName("UniformNoiseButton")
        self.SaltPepperNoiseButton = QtWidgets.QPushButton(self.Noise)
        self.SaltPepperNoiseButton.setGeometry(QtCore.QRect(10, 20, 221, 51))
        self.SaltPepperNoiseButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.SaltPepperNoiseButton.setObjectName("SaltPepperNoiseButton")
        self.GaussianNoiseButton = QtWidgets.QPushButton(self.Noise)
        self.GaussianNoiseButton.setGeometry(QtCore.QRect(10, 140, 221, 51))
        self.GaussianNoiseButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.GaussianNoiseButton.setObjectName("GaussianNoiseButton")
        self.FilterLabel = QtWidgets.QLabel(self.FilterTab)
        self.FilterLabel.setGeometry(QtCore.QRect(30, 90, 241, 31))
        self.FilterLabel.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.FilterLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.FilterLabel.setObjectName("FilterLabel")
        self.NoiseLabel = QtWidgets.QLabel(self.FilterTab)
        self.NoiseLabel.setGeometry(QtCore.QRect(30, 360, 241, 31))
        self.NoiseLabel.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.NoiseLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NoiseLabel.setObjectName("NoiseLabel")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/FilterIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.FilterTab, icon1, "")
        self.EdgeDetection = QtWidgets.QWidget()
        self.EdgeDetection.setObjectName("EdgeDetection")
        self.ImagesFrame_2 = QtWidgets.QFrame(self.EdgeDetection)
        self.ImagesFrame_2.setGeometry(QtCore.QRect(280, 50, 1121, 571))
        self.ImagesFrame_2.setStyleSheet("background-color: transparent;\n"
"border-radius:5px;")
        self.ImagesFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ImagesFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ImagesFrame_2.setObjectName("ImagesFrame_2")
        self.outputImageLabel_2 = QtWidgets.QLabel(self.ImagesFrame_2)
        self.outputImageLabel_2.setGeometry(QtCore.QRect(750, 10, 191, 31))
        self.outputImageLabel_2.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.outputImageLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.outputImageLabel_2.setObjectName("outputImageLabel_2")
        self.inputImageLabel_2 = QtWidgets.QLabel(self.ImagesFrame_2)
        self.inputImageLabel_2.setGeometry(QtCore.QRect(170, 10, 191, 31))
        self.inputImageLabel_2.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.inputImageLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.inputImageLabel_2.setObjectName("inputImageLabel_2")
        self.EdgeDetection_inputImage = QtWidgets.QLabel(self.ImagesFrame_2)
        self.EdgeDetection_inputImage.setGeometry(QtCore.QRect(20, 50, 512, 512))
        self.EdgeDetection_inputImage.setStyleSheet("border: 4px solid black;\n"
"")
        self.EdgeDetection_inputImage.setText("")
        self.EdgeDetection_inputImage.setScaledContents(True)
        self.EdgeDetection_inputImage.setAlignment(QtCore.Qt.AlignCenter)
        self.EdgeDetection_inputImage.setObjectName("EdgeDetection_inputImage")
        self.EdgeDetection_outputImage = QtWidgets.QLabel(self.ImagesFrame_2)
        self.EdgeDetection_outputImage.setGeometry(QtCore.QRect(580, 50, 512, 512))
        self.EdgeDetection_outputImage.setStyleSheet("border: 4px solid black;\n"
"")
        self.EdgeDetection_outputImage.setText("")
        self.EdgeDetection_outputImage.setScaledContents(True)
        self.EdgeDetection_outputImage.setAlignment(QtCore.Qt.AlignCenter)
        self.EdgeDetection_outputImage.setObjectName("EdgeDetection_outputImage")
        self.Prewitt = QtWidgets.QWidget(self.EdgeDetection)
        self.Prewitt.setGeometry(QtCore.QRect(20, 100, 251, 111))
        self.Prewitt.setStyleSheet("border: 2px solid;\n"
"border-radius: 5px;")
        self.Prewitt.setObjectName("Prewitt")
        self.PrewittButton = QtWidgets.QPushButton(self.Prewitt)
        self.PrewittButton.setGeometry(QtCore.QRect(20, 50, 211, 51))
        self.PrewittButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.PrewittButton.setObjectName("PrewittButton")
        self.label = QtWidgets.QLabel(self.Prewitt)
        self.label.setGeometry(QtCore.QRect(0, 10, 241, 31))
        self.label.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Robert = QtWidgets.QWidget(self.EdgeDetection)
        self.Robert.setGeometry(QtCore.QRect(20, 220, 251, 121))
        self.Robert.setStyleSheet("border: 2px solid;\n"
"border-radius: 5px;")
        self.Robert.setObjectName("Robert")
        self.label_2 = QtWidgets.QLabel(self.Robert)
        self.label_2.setGeometry(QtCore.QRect(0, 10, 241, 31))
        self.label_2.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.RobetButton = QtWidgets.QPushButton(self.Robert)
        self.RobetButton.setGeometry(QtCore.QRect(20, 50, 211, 51))
        self.RobetButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.RobetButton.setObjectName("RobetButton")
        self.Sobel = QtWidgets.QWidget(self.EdgeDetection)
        self.Sobel.setGeometry(QtCore.QRect(20, 360, 251, 121))
        self.Sobel.setStyleSheet("border: 2px solid;\n"
"border-radius: 5px;")
        self.Sobel.setObjectName("Sobel")
        self.label_3 = QtWidgets.QLabel(self.Sobel)
        self.label_3.setGeometry(QtCore.QRect(0, 10, 241, 31))
        self.label_3.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.SobelButton = QtWidgets.QPushButton(self.Sobel)
        self.SobelButton.setGeometry(QtCore.QRect(20, 50, 211, 51))
        self.SobelButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.SobelButton.setObjectName("SobelButton")
        self.Canny = QtWidgets.QWidget(self.EdgeDetection)
        self.Canny.setGeometry(QtCore.QRect(20, 490, 251, 121))
        self.Canny.setStyleSheet("border: 2px solid;\n"
"border-radius: 5px;")
        self.Canny.setObjectName("Canny")
        self.label_4 = QtWidgets.QLabel(self.Canny)
        self.label_4.setGeometry(QtCore.QRect(0, 10, 241, 31))
        self.label_4.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.CannyButton = QtWidgets.QPushButton(self.Canny)
        self.CannyButton.setGeometry(QtCore.QRect(20, 50, 211, 51))
        self.CannyButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.CannyButton.setObjectName("CannyButton")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/edge_detection.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.EdgeDetection, icon2, "")
        self.PassTab = QtWidgets.QWidget()
        self.PassTab.setObjectName("PassTab")
        self.outputImageLabel_7 = QtWidgets.QLabel(self.PassTab)
        self.outputImageLabel_7.setGeometry(QtCore.QRect(1000, 50, 191, 31))
        self.outputImageLabel_7.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.outputImageLabel_7.setAlignment(QtCore.Qt.AlignCenter)
        self.outputImageLabel_7.setObjectName("outputImageLabel_7")
        self.inputImageLabel_11 = QtWidgets.QLabel(self.PassTab)
        self.inputImageLabel_11.setGeometry(QtCore.QRect(420, 50, 191, 31))
        self.inputImageLabel_11.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.inputImageLabel_11.setAlignment(QtCore.Qt.AlignCenter)
        self.inputImageLabel_11.setObjectName("inputImageLabel_11")
        self.pass_inputImage = QtWidgets.QLabel(self.PassTab)
        self.pass_inputImage.setGeometry(QtCore.QRect(290, 90, 512, 512))
        self.pass_inputImage.setStyleSheet("border: 4px solid black;\n"
"")
        self.pass_inputImage.setText("")
        self.pass_inputImage.setScaledContents(True)
        self.pass_inputImage.setAlignment(QtCore.Qt.AlignCenter)
        self.pass_inputImage.setObjectName("pass_inputImage")
        self.pass_outputImage = QtWidgets.QLabel(self.PassTab)
        self.pass_outputImage.setGeometry(QtCore.QRect(830, 90, 512, 512))
        self.pass_outputImage.setStyleSheet("border: 4px solid black;\n"
"")
        self.pass_outputImage.setText("")
        self.pass_outputImage.setScaledContents(True)
        self.pass_outputImage.setAlignment(QtCore.Qt.AlignCenter)
        self.pass_outputImage.setObjectName("pass_outputImage")
        self.FilterLabel_3 = QtWidgets.QLabel(self.PassTab)
        self.FilterLabel_3.setGeometry(QtCore.QRect(20, 130, 241, 31))
        self.FilterLabel_3.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.FilterLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.FilterLabel_3.setObjectName("FilterLabel_3")
        self.Filtering_3 = QtWidgets.QWidget(self.PassTab)
        self.Filtering_3.setGeometry(QtCore.QRect(20, 170, 241, 221))
        self.Filtering_3.setStyleSheet("QWidget{\n"
"border: 2px solid;\n"
"border-radius: 5px;\n"
"}")
        self.Filtering_3.setObjectName("Filtering_3")
        self.LowpassButton = QtWidgets.QPushButton(self.Filtering_3)
        self.LowpassButton.setGeometry(QtCore.QRect(10, 90, 221, 51))
        self.LowpassButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.LowpassButton.setObjectName("LowpassButton")
        self.HighpassButton = QtWidgets.QPushButton(self.Filtering_3)
        self.HighpassButton.setGeometry(QtCore.QRect(10, 30, 221, 51))
        self.HighpassButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.HighpassButton.setObjectName("HighpassButton")
        self.horizontalSlider = QtWidgets.QSlider(self.Filtering_3)
        self.horizontalSlider.setGeometry(QtCore.QRect(40, 160, 160, 18))
        self.horizontalSlider.setMaximum(2000)
        self.horizontalSlider.setSliderPosition(1000)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_5 = QtWidgets.QLabel(self.Filtering_3)
        self.label_5.setGeometry(QtCore.QRect(130, 190, 41, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.Filtering_3)
        self.label_8.setGeometry(QtCore.QRect(40, 190, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.PassTab, "")
        self.HistogramTab = QtWidgets.QWidget()
        self.HistogramTab.setObjectName("HistogramTab")
        self.A6 = QtWidgets.QLabel(self.HistogramTab)
        self.A6.setGeometry(QtCore.QRect(180, 20, 111, 31))
        self.A6.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.A6.setAlignment(QtCore.Qt.AlignCenter)
        self.A6.setObjectName("A6")
        self.Histogram_1 = QtWidgets.QLabel(self.HistogramTab)
        self.Histogram_1.setGeometry(QtCore.QRect(30, 60, 421, 241))
        self.Histogram_1.setStyleSheet("border: 4px solid black;\n"
"")
        self.Histogram_1.setText("")
        self.Histogram_1.setScaledContents(True)
        self.Histogram_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Histogram_1.setObjectName("Histogram_1")
        self.A6_2 = QtWidgets.QLabel(self.HistogramTab)
        self.A6_2.setGeometry(QtCore.QRect(180, 320, 111, 31))
        self.A6_2.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.A6_2.setAlignment(QtCore.Qt.AlignCenter)
        self.A6_2.setObjectName("A6_2")
        self.Histogram_2 = QtWidgets.QLabel(self.HistogramTab)
        self.Histogram_2.setGeometry(QtCore.QRect(30, 360, 421, 241))
        self.Histogram_2.setStyleSheet("border: 4px solid black;\n"
"")
        self.Histogram_2.setText("")
        self.Histogram_2.setScaledContents(True)
        self.Histogram_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Histogram_2.setObjectName("Histogram_2")
        self.Histogram_3 = QtWidgets.QLabel(self.HistogramTab)
        self.Histogram_3.setGeometry(QtCore.QRect(490, 60, 421, 241))
        self.Histogram_3.setStyleSheet("border: 4px solid black;\n"
"")
        self.Histogram_3.setText("")
        self.Histogram_3.setScaledContents(True)
        self.Histogram_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Histogram_3.setObjectName("Histogram_3")
        self.A6_3 = QtWidgets.QLabel(self.HistogramTab)
        self.A6_3.setGeometry(QtCore.QRect(640, 320, 111, 31))
        self.A6_3.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.A6_3.setAlignment(QtCore.Qt.AlignCenter)
        self.A6_3.setObjectName("A6_3")
        self.Histogram_4 = QtWidgets.QLabel(self.HistogramTab)
        self.Histogram_4.setGeometry(QtCore.QRect(490, 360, 421, 241))
        self.Histogram_4.setStyleSheet("border: 4px solid black;\n"
"")
        self.Histogram_4.setText("")
        self.Histogram_4.setScaledContents(True)
        self.Histogram_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Histogram_4.setObjectName("Histogram_4")
        self.A6_4 = QtWidgets.QLabel(self.HistogramTab)
        self.A6_4.setGeometry(QtCore.QRect(640, 20, 111, 31))
        self.A6_4.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.A6_4.setAlignment(QtCore.Qt.AlignCenter)
        self.A6_4.setObjectName("A6_4")
        self.Histogram_5 = QtWidgets.QLabel(self.HistogramTab)
        self.Histogram_5.setGeometry(QtCore.QRect(950, 60, 421, 241))
        self.Histogram_5.setStyleSheet("border: 4px solid black;\n"
"")
        self.Histogram_5.setText("")
        self.Histogram_5.setScaledContents(True)
        self.Histogram_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Histogram_5.setObjectName("Histogram_5")
        self.A6_5 = QtWidgets.QLabel(self.HistogramTab)
        self.A6_5.setGeometry(QtCore.QRect(1100, 320, 141, 31))
        self.A6_5.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.A6_5.setAlignment(QtCore.Qt.AlignCenter)
        self.A6_5.setObjectName("A6_5")
        self.Histogram_6 = QtWidgets.QLabel(self.HistogramTab)
        self.Histogram_6.setGeometry(QtCore.QRect(950, 360, 421, 241))
        self.Histogram_6.setStyleSheet("border: 4px solid black;\n"
"")
        self.Histogram_6.setText("")
        self.Histogram_6.setScaledContents(True)
        self.Histogram_6.setAlignment(QtCore.Qt.AlignCenter)
        self.Histogram_6.setObjectName("Histogram_6")
        self.A6_6 = QtWidgets.QLabel(self.HistogramTab)
        self.A6_6.setGeometry(QtCore.QRect(1100, 20, 131, 31))
        self.A6_6.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.A6_6.setAlignment(QtCore.Qt.AlignCenter)
        self.A6_6.setObjectName("A6_6")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Histogram.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.HistogramTab, icon3, "")
        self.ThresholdTab = QtWidgets.QWidget()
        self.ThresholdTab.setEnabled(True)
        self.ThresholdTab.setObjectName("ThresholdTab")
        self.ImagesFrame_3 = QtWidgets.QFrame(self.ThresholdTab)
        self.ImagesFrame_3.setGeometry(QtCore.QRect(280, 50, 1121, 571))
        self.ImagesFrame_3.setStyleSheet("background-color: transparent;\n"
"border-radius:5px;")
        self.ImagesFrame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ImagesFrame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ImagesFrame_3.setObjectName("ImagesFrame_3")
        self.outputImageLabel_3 = QtWidgets.QLabel(self.ImagesFrame_3)
        self.outputImageLabel_3.setGeometry(QtCore.QRect(750, 10, 191, 31))
        self.outputImageLabel_3.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.outputImageLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.outputImageLabel_3.setObjectName("outputImageLabel_3")
        self.inputImageLabel_3 = QtWidgets.QLabel(self.ImagesFrame_3)
        self.inputImageLabel_3.setGeometry(QtCore.QRect(170, 10, 191, 31))
        self.inputImageLabel_3.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.inputImageLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.inputImageLabel_3.setObjectName("inputImageLabel_3")
        self.Threshold_inputImage = QtWidgets.QLabel(self.ImagesFrame_3)
        self.Threshold_inputImage.setGeometry(QtCore.QRect(20, 50, 512, 512))
        self.Threshold_inputImage.setStyleSheet("border: 4px solid black;\n"
"")
        self.Threshold_inputImage.setText("")
        self.Threshold_inputImage.setScaledContents(True)
        self.Threshold_inputImage.setAlignment(QtCore.Qt.AlignCenter)
        self.Threshold_inputImage.setObjectName("Threshold_inputImage")
        self.Threshold_outputImage = QtWidgets.QLabel(self.ImagesFrame_3)
        self.Threshold_outputImage.setGeometry(QtCore.QRect(580, 50, 512, 512))
        self.Threshold_outputImage.setStyleSheet("border: 4px solid black;\n"
"")
        self.Threshold_outputImage.setText("")
        self.Threshold_outputImage.setScaledContents(True)
        self.Threshold_outputImage.setAlignment(QtCore.Qt.AlignCenter)
        self.Threshold_outputImage.setObjectName("Threshold_outputImage")
        self.LocalThershold = QtWidgets.QWidget(self.ThresholdTab)
        self.LocalThershold.setGeometry(QtCore.QRect(30, 80, 241, 141))
        self.LocalThershold.setStyleSheet("border: 2px solid;\n"
"border-radius: 5px;")
        self.LocalThershold.setObjectName("LocalThershold")
        self.LocalThresholdButton = QtWidgets.QPushButton(self.LocalThershold)
        self.LocalThresholdButton.setGeometry(QtCore.QRect(50, 80, 151, 51))
        self.LocalThresholdButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.LocalThresholdButton.setObjectName("LocalThresholdButton")
        self.LocalLabel = QtWidgets.QLabel(self.LocalThershold)
        self.LocalLabel.setGeometry(QtCore.QRect(0, 10, 241, 31))
        self.LocalLabel.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.LocalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LocalLabel.setObjectName("LocalLabel")
        self.Radio5x5Kernal_2 = QtWidgets.QRadioButton(self.LocalThershold)
        self.Radio5x5Kernal_2.setGeometry(QtCore.QRect(130, 50, 50, 20))
        self.Radio5x5Kernal_2.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 15px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.Radio5x5Kernal_2.setObjectName("Radio5x5Kernal_2")
        self.Radio3x3Kernal_2 = QtWidgets.QRadioButton(self.LocalThershold)
        self.Radio3x3Kernal_2.setGeometry(QtCore.QRect(60, 50, 50, 20))
        self.Radio3x3Kernal_2.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 15px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.Radio3x3Kernal_2.setChecked(True)
        self.Radio3x3Kernal_2.setObjectName("Radio3x3Kernal_2")
        self.GlobalThreshold = QtWidgets.QWidget(self.ThresholdTab)
        self.GlobalThreshold.setGeometry(QtCore.QRect(30, 230, 241, 121))
        self.GlobalThreshold.setStyleSheet("border: 2px solid;\n"
"border-radius: 5px;")
        self.GlobalThreshold.setObjectName("GlobalThreshold")
        self.GlobalThresholdButton = QtWidgets.QPushButton(self.GlobalThreshold)
        self.GlobalThresholdButton.setGeometry(QtCore.QRect(50, 50, 151, 51))
        self.GlobalThresholdButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.GlobalThresholdButton.setObjectName("GlobalThresholdButton")
        self.GlobalLabel = QtWidgets.QLabel(self.GlobalThreshold)
        self.GlobalLabel.setGeometry(QtCore.QRect(0, 10, 241, 31))
        self.GlobalLabel.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.GlobalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.GlobalLabel.setObjectName("GlobalLabel")
        self.Normalize = QtWidgets.QWidget(self.ThresholdTab)
        self.Normalize.setGeometry(QtCore.QRect(30, 360, 241, 121))
        self.Normalize.setStyleSheet("border: 2px solid;\n"
"border-radius: 5px;")
        self.Normalize.setObjectName("Normalize")
        self.NormalizeButton = QtWidgets.QPushButton(self.Normalize)
        self.NormalizeButton.setGeometry(QtCore.QRect(50, 50, 151, 51))
        self.NormalizeButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.NormalizeButton.setObjectName("NormalizeButton")
        self.NormalizeLabel = QtWidgets.QLabel(self.Normalize)
        self.NormalizeLabel.setGeometry(QtCore.QRect(0, 10, 241, 31))
        self.NormalizeLabel.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.NormalizeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NormalizeLabel.setObjectName("NormalizeLabel")
        self.Equalize = QtWidgets.QWidget(self.ThresholdTab)
        self.Equalize.setGeometry(QtCore.QRect(30, 490, 241, 121))
        self.Equalize.setStyleSheet("border: 2px solid;\n"
"border-radius: 5px;")
        self.Equalize.setObjectName("Equalize")
        self.EqualizeButton = QtWidgets.QPushButton(self.Equalize)
        self.EqualizeButton.setGeometry(QtCore.QRect(50, 50, 151, 51))
        self.EqualizeButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.EqualizeButton.setObjectName("EqualizeButton")
        self.EqualizeLabel = QtWidgets.QLabel(self.Equalize)
        self.EqualizeLabel.setGeometry(QtCore.QRect(0, 10, 241, 31))
        self.EqualizeLabel.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.EqualizeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.EqualizeLabel.setObjectName("EqualizeLabel")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Threshold.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.ThresholdTab, icon4, "")
        self.Frequency = QtWidgets.QWidget()
        self.Frequency.setObjectName("Frequency")
        self.hybridInputImage1 = QtWidgets.QLabel(self.Frequency)
        self.hybridInputImage1.setGeometry(QtCore.QRect(60, 60, 256, 256))
        self.hybridInputImage1.setStyleSheet("border: 4px solid black;\n"
"")
        self.hybridInputImage1.setText("")
        self.hybridInputImage1.setScaledContents(True)
        self.hybridInputImage1.setAlignment(QtCore.Qt.AlignCenter)
        self.hybridInputImage1.setObjectName("hybridInputImage1")
        self.freqOutputImage1 = QtWidgets.QLabel(self.Frequency)
        self.freqOutputImage1.setGeometry(QtCore.QRect(410, 60, 256, 256))
        self.freqOutputImage1.setStyleSheet("border: 4px solid black;\n"
"")
        self.freqOutputImage1.setText("")
        self.freqOutputImage1.setScaledContents(True)
        self.freqOutputImage1.setAlignment(QtCore.Qt.AlignCenter)
        self.freqOutputImage1.setObjectName("freqOutputImage1")
        self.hybridInputImage2 = QtWidgets.QLabel(self.Frequency)
        self.hybridInputImage2.setGeometry(QtCore.QRect(60, 350, 256, 256))
        self.hybridInputImage2.setStyleSheet("border: 4px solid black;\n"
"")
        self.hybridInputImage2.setText("")
        self.hybridInputImage2.setScaledContents(True)
        self.hybridInputImage2.setAlignment(QtCore.Qt.AlignCenter)
        self.hybridInputImage2.setObjectName("hybridInputImage2")
        self.freqOutputImage2 = QtWidgets.QLabel(self.Frequency)
        self.freqOutputImage2.setGeometry(QtCore.QRect(410, 350, 256, 256))
        self.freqOutputImage2.setStyleSheet("border: 4px solid black;\n"
"")
        self.freqOutputImage2.setText("")
        self.freqOutputImage2.setScaledContents(True)
        self.freqOutputImage2.setAlignment(QtCore.Qt.AlignCenter)
        self.freqOutputImage2.setObjectName("freqOutputImage2")
        self.UploadeImage1 = QtWidgets.QPushButton(self.Frequency)
        self.UploadeImage1.setGeometry(QtCore.QRect(330, 50, 61, 61))
        self.UploadeImage1.setStyleSheet("QPushButton{\n"
"border-radius: 25px;\n"
"font: 900 12pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.UploadeImage1.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/UploadIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UploadeImage1.setIcon(icon5)
        self.UploadeImage1.setIconSize(QtCore.QSize(60, 60))
        self.UploadeImage1.setObjectName("UploadeImage1")
        self.finalHybridImage = QtWidgets.QLabel(self.Frequency)
        self.finalHybridImage.setGeometry(QtCore.QRect(780, 114, 512, 491))
        self.finalHybridImage.setStyleSheet("border: 4px solid black;\n"
"")
        self.finalHybridImage.setText("")
        self.finalHybridImage.setScaledContents(True)
        self.finalHybridImage.setAlignment(QtCore.Qt.AlignCenter)
        self.finalHybridImage.setObjectName("finalHybridImage")
        self.inputImageLabel_4 = QtWidgets.QLabel(self.Frequency)
        self.inputImageLabel_4.setGeometry(QtCore.QRect(90, 30, 191, 31))
        self.inputImageLabel_4.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color:transparent;")
        self.inputImageLabel_4.setAlignment(QtCore.Qt.AlignCenter)
        self.inputImageLabel_4.setObjectName("inputImageLabel_4")
        self.inputImageLabel_5 = QtWidgets.QLabel(self.Frequency)
        self.inputImageLabel_5.setGeometry(QtCore.QRect(90, 320, 191, 31))
        self.inputImageLabel_5.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color:transparent;")
        self.inputImageLabel_5.setAlignment(QtCore.Qt.AlignCenter)
        self.inputImageLabel_5.setObjectName("inputImageLabel_5")
        self.BrowseButton_2 = QtWidgets.QPushButton(self.Frequency)
        self.BrowseButton_2.setGeometry(QtCore.QRect(250, 320, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.BrowseButton_2.setFont(font)
        self.BrowseButton_2.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"text-align: left;\n"
"font: 900 12pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"")
        self.BrowseButton_2.setIcon(icon5)
        self.BrowseButton_2.setIconSize(QtCore.QSize(50, 50))
        self.BrowseButton_2.setObjectName("BrowseButton_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.Frequency)
        self.radioButton_2.setGeometry(QtCore.QRect(890, 50, 141, 41))
        font = QtGui.QFont()
        font.setBold(True)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.GenerateHybrid = QtWidgets.QPushButton(self.Frequency)
        self.GenerateHybrid.setGeometry(QtCore.QRect(1070, 50, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.GenerateHybrid.setFont(font)
        self.GenerateHybrid.setObjectName("GenerateHybrid")
        self.label_7 = QtWidgets.QLabel(self.Frequency)
        self.label_7.setGeometry(QtCore.QRect(690, 450, 61, 41))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.Frequency)
        self.label_6.setGeometry(QtCore.QRect(680, 260, 81, 41))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.VerticalSlider = QtWidgets.QSlider(self.Frequency)
        self.VerticalSlider.setGeometry(QtCore.QRect(710, 300, 21, 141))
        self.VerticalSlider.setMaximum(2000)
        self.VerticalSlider.setPageStep(10)
        self.VerticalSlider.setSliderPosition(1000)
        self.VerticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.VerticalSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.VerticalSlider.setTickInterval(0)
        self.VerticalSlider.setObjectName("VerticalSlider")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/hybrid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Frequency, icon6, "")
        self.BrowseButton = QtWidgets.QPushButton(self.centralwidget)
        self.BrowseButton.setGeometry(QtCore.QRect(1130, 20, 141, 61))
        self.BrowseButton.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"text-align: left;\n"
"font: 900 12pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"")
        self.BrowseButton.setIcon(icon5)
        self.BrowseButton.setIconSize(QtCore.QSize(50, 50))
        self.BrowseButton.setObjectName("BrowseButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.outputImageLabel.setText(_translate("MainWindow", "Output "))
        self.inputImageLabel.setText(_translate("MainWindow", "Input"))
        self.RefreshButton.setText(_translate("MainWindow", "Refresh"))
        self.AverageFilterButton.setText(_translate("MainWindow", "Average Filter"))
        self.MedianFilterButton.setText(_translate("MainWindow", "Median Filter"))
        self.GaussianFilterButton.setText(_translate("MainWindow", "Gaussian Filter"))
        self.Radio3x3Kernal.setText(_translate("MainWindow", "3x3"))
        self.Radio5x5Kernal.setText(_translate("MainWindow", "5x5"))
        self.UniformNoiseButton.setText(_translate("MainWindow", "Uniform Noise"))
        self.SaltPepperNoiseButton.setText(_translate("MainWindow", "Salt and Pepper Noise"))
        self.GaussianNoiseButton.setText(_translate("MainWindow", "Gaussian Noise"))
        self.FilterLabel.setText(_translate("MainWindow", "Filter Types"))
        self.NoiseLabel.setText(_translate("MainWindow", "Noise Types"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.FilterTab), _translate("MainWindow", "Filter"))
        self.outputImageLabel_2.setText(_translate("MainWindow", "Output "))
        self.inputImageLabel_2.setText(_translate("MainWindow", "Input"))
        self.PrewittButton.setText(_translate("MainWindow", "Prewitt Edge Technique"))
        self.label.setText(_translate("MainWindow", "Prewitt"))
        self.label_2.setText(_translate("MainWindow", "Robert"))
        self.RobetButton.setText(_translate("MainWindow", "Robert Edge Technique"))
        self.label_3.setText(_translate("MainWindow", "Sobel"))
        self.SobelButton.setText(_translate("MainWindow", "Sobel Edge Technique"))
        self.label_4.setText(_translate("MainWindow", "Canny"))
        self.CannyButton.setText(_translate("MainWindow", "Canny Edge Technique"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.EdgeDetection), _translate("MainWindow", "Edge Detection"))
        self.outputImageLabel_7.setText(_translate("MainWindow", "Output "))
        self.inputImageLabel_11.setText(_translate("MainWindow", "Input"))
        self.FilterLabel_3.setText(_translate("MainWindow", "Filter Types"))
        self.LowpassButton.setText(_translate("MainWindow", "Low Pass"))
        self.HighpassButton.setText(_translate("MainWindow", "High Pass "))
        self.label_5.setText(_translate("MainWindow", "1000"))
        self.label_8.setText(_translate("MainWindow", "Cutoff freq"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PassTab), _translate("MainWindow", "HPF - LPF"))
        self.A6.setText(_translate("MainWindow", "Red DF"))
        self.A6_2.setText(_translate("MainWindow", "Red CDF"))
        self.A6_3.setText(_translate("MainWindow", "Blue CDF"))
        self.A6_4.setText(_translate("MainWindow", "Blue DF"))
        self.A6_5.setText(_translate("MainWindow", "Green CDF"))
        self.A6_6.setText(_translate("MainWindow", "Green DF"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.HistogramTab), _translate("MainWindow", "Histogram"))
        self.outputImageLabel_3.setText(_translate("MainWindow", "Output "))
        self.inputImageLabel_3.setText(_translate("MainWindow", "Input"))
        self.LocalThresholdButton.setText(_translate("MainWindow", "Apply"))
        self.LocalLabel.setText(_translate("MainWindow", "Local Threshold"))
        self.Radio5x5Kernal_2.setText(_translate("MainWindow", "5x5"))
        self.Radio3x3Kernal_2.setText(_translate("MainWindow", "3x3"))
        self.GlobalThresholdButton.setText(_translate("MainWindow", "Apply"))
        self.GlobalLabel.setText(_translate("MainWindow", "Global Threshold"))
        self.NormalizeButton.setText(_translate("MainWindow", "Apply"))
        self.NormalizeLabel.setText(_translate("MainWindow", "Normalize"))
        self.EqualizeButton.setText(_translate("MainWindow", "Apply"))
        self.EqualizeLabel.setText(_translate("MainWindow", "Equalize"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ThresholdTab), _translate("MainWindow", "Threshold"))
        self.inputImageLabel_4.setText(_translate("MainWindow", "Image 1"))
        self.inputImageLabel_5.setText(_translate("MainWindow", "Image 2"))
        self.BrowseButton_2.setText(_translate("MainWindow", "Upload Image"))
        self.radioButton_2.setText(_translate("MainWindow", "Switch HPF/LPF"))
        self.GenerateHybrid.setText(_translate("MainWindow", "Generate"))
        self.label_7.setText(_translate("MainWindow", "1000"))
        self.label_6.setText(_translate("MainWindow", "Cutoff freq"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Frequency), _translate("MainWindow", "Hybrid"))
        self.BrowseButton.setText(_translate("MainWindow", "Upload Image"))
