# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1394, 716)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1394, 716))
        MainWindow.setMaximumSize(QtCore.QSize(1394, 716))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1451, 721))
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"  border: 1px solid lightgray;\n"
"  top:-1px; \n"
"  background: rgb(245, 245, 245);; \n"
"} \n"
"\n"
"QTabBar::tab {\n"
"  background: rgb(230, 230, 230); \n"
"  border: 1px solid lightgray; \n"
"  padding: 15px;\n"
"  border-radius: 4px;\n"
"\n"
"  font: 900 15pt \"Segoe UI Black\";\n"
"} \n"
"\n"
"QTabBar::tab:selected { \n"
"  background: rgb(245, 245, 245); \n"
"  margin-bottom: -1px; \n"
"}\n"
"")
        self.tabWidget.setIconSize(QtCore.QSize(30, 30))
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName("tabWidget")
        self.FilterTab = QtWidgets.QWidget()
        self.FilterTab.setObjectName("FilterTab")
        self.ImagesFrame = QtWidgets.QFrame(self.FilterTab)
        self.ImagesFrame.setGeometry(QtCore.QRect(280, 50, 1121, 571))
        self.ImagesFrame.setStyleSheet("background-color: transparent;\n"
"border-radius:5px;")
        self.ImagesFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ImagesFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ImagesFrame.setObjectName("ImagesFrame")
        self.outputImageLabel = QtWidgets.QLabel(self.ImagesFrame)
        self.outputImageLabel.setGeometry(QtCore.QRect(750, 10, 191, 31))
        self.outputImageLabel.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.outputImageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.outputImageLabel.setObjectName("outputImageLabel")
        self.inputImageLabel = QtWidgets.QLabel(self.ImagesFrame)
        self.inputImageLabel.setGeometry(QtCore.QRect(170, 10, 191, 31))
        self.inputImageLabel.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.inputImageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.inputImageLabel.setObjectName("inputImageLabel")
        self.filter_inputImage = QtWidgets.QLabel(self.ImagesFrame)
        self.filter_inputImage.setGeometry(QtCore.QRect(20, 50, 512, 512))
        self.filter_inputImage.setStyleSheet("border: 4px solid black;\n"
"")
        self.filter_inputImage.setText("")
        self.filter_inputImage.setScaledContents(True)
        self.filter_inputImage.setAlignment(QtCore.Qt.AlignCenter)
        self.filter_inputImage.setObjectName("filter_inputImage")
        self.filter_outputImage = QtWidgets.QLabel(self.ImagesFrame)
        self.filter_outputImage.setGeometry(QtCore.QRect(580, 50, 512, 512))
        self.filter_outputImage.setStyleSheet("border: 4px solid black;\n"
"")
        self.filter_outputImage.setText("")
        self.filter_outputImage.setScaledContents(True)
        self.filter_outputImage.setAlignment(QtCore.Qt.AlignCenter)
        self.filter_outputImage.setObjectName("filter_outputImage")
        self.GrayScale = QtWidgets.QPushButton(self.FilterTab)
        self.GrayScale.setGeometry(QtCore.QRect(1320, 20, 51, 51))
        self.GrayScale.setStyleSheet("QPushButton{\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.GrayScale.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/convert_color_to_gray.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.GrayScale.setIcon(icon)
        self.GrayScale.setIconSize(QtCore.QSize(50, 50))
        self.GrayScale.setObjectName("GrayScale")
        self.Filtering = QtWidgets.QWidget(self.FilterTab)
        self.Filtering.setGeometry(QtCore.QRect(30, 130, 241, 221))
        self.Filtering.setStyleSheet("QWidget{\n"
"border: 2px solid;\n"
"border-radius: 5px;\n"
"}")
        self.Filtering.setObjectName("Filtering")
        self.AverageFilterButton = QtWidgets.QPushButton(self.Filtering)
        self.AverageFilterButton.setGeometry(QtCore.QRect(10, 90, 221, 51))
        self.AverageFilterButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.AverageFilterButton.setObjectName("AverageFilterButton")
        self.MedianFilterButton = QtWidgets.QPushButton(self.Filtering)
        self.MedianFilterButton.setGeometry(QtCore.QRect(10, 30, 221, 51))
        self.MedianFilterButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.MedianFilterButton.setObjectName("MedianFilterButton")
        self.GaussianFilterButton = QtWidgets.QPushButton(self.Filtering)
        self.GaussianFilterButton.setGeometry(QtCore.QRect(10, 150, 221, 51))
        self.GaussianFilterButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.GaussianFilterButton.setObjectName("GaussianFilterButton")
        self.Radio3x3Kernal = QtWidgets.QRadioButton(self.Filtering)
        self.Radio3x3Kernal.setGeometry(QtCore.QRect(60, 5, 50, 20))
        self.Radio3x3Kernal.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 15px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.Radio3x3Kernal.setChecked(True)
        self.Radio3x3Kernal.setObjectName("Radio3x3Kernal")
        self.Radio5x5Kernal = QtWidgets.QRadioButton(self.Filtering)
        self.Radio5x5Kernal.setGeometry(QtCore.QRect(130, 5, 50, 20))
        self.Radio5x5Kernal.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 15px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.Radio5x5Kernal.setObjectName("Radio5x5Kernal")
        self.Noise = QtWidgets.QWidget(self.FilterTab)
        self.Noise.setGeometry(QtCore.QRect(30, 400, 241, 211))
        self.Noise.setStyleSheet("border: 2px solid;\n"
"border-radius: 5px;")
        self.Noise.setObjectName("Noise")
        self.UniformNoiseButton = QtWidgets.QPushButton(self.Noise)
        self.UniformNoiseButton.setGeometry(QtCore.QRect(10, 80, 221, 51))
        self.UniformNoiseButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.UniformNoiseButton.setObjectName("UniformNoiseButton")
        self.SaltPepperNoiseButton = QtWidgets.QPushButton(self.Noise)
        self.SaltPepperNoiseButton.setGeometry(QtCore.QRect(10, 20, 221, 51))
        self.SaltPepperNoiseButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.SaltPepperNoiseButton.setObjectName("SaltPepperNoiseButton")
        self.GaussianNoiseButton = QtWidgets.QPushButton(self.Noise)
        self.GaussianNoiseButton.setGeometry(QtCore.QRect(10, 140, 221, 51))
        self.GaussianNoiseButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.GaussianNoiseButton.setObjectName("GaussianNoiseButton")
        self.FilterLabel = QtWidgets.QLabel(self.FilterTab)
        self.FilterLabel.setGeometry(QtCore.QRect(30, 90, 241, 31))
        self.FilterLabel.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.FilterLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.FilterLabel.setObjectName("FilterLabel")
        self.NoiseLabel = QtWidgets.QLabel(self.FilterTab)
        self.NoiseLabel.setGeometry(QtCore.QRect(30, 360, 241, 31))
        self.NoiseLabel.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.NoiseLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NoiseLabel.setObjectName("NoiseLabel")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/FilterIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.FilterTab, icon1, "")
        self.HistogramTab = QtWidgets.QWidget()
        self.HistogramTab.setObjectName("HistogramTab")
        self.A6 = QtWidgets.QLabel(self.HistogramTab)
        self.A6.setGeometry(QtCore.QRect(500, 10, 400, 31))
        self.A6.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.A6.setAlignment(QtCore.Qt.AlignCenter)
        self.A6.setObjectName("A6")
        self.A5 = QtWidgets.QLabel(self.HistogramTab)
        self.A5.setGeometry(QtCore.QRect(500, 340, 400, 31))
        self.A5.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.A5.setAlignment(QtCore.Qt.AlignCenter)
        self.A5.setObjectName("A5")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Histogram.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.HistogramTab, icon2, "")
        self.EdgeDetection = QtWidgets.QWidget()
        self.EdgeDetection.setObjectName("EdgeDetection")
        self.ImagesFrame_2 = QtWidgets.QFrame(self.EdgeDetection)
        self.ImagesFrame_2.setGeometry(QtCore.QRect(280, 50, 1121, 571))
        self.ImagesFrame_2.setStyleSheet("background-color: transparent;\n"
"border-radius:5px;")
        self.ImagesFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ImagesFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ImagesFrame_2.setObjectName("ImagesFrame_2")
        self.outputImageLabel_2 = QtWidgets.QLabel(self.ImagesFrame_2)
        self.outputImageLabel_2.setGeometry(QtCore.QRect(750, 10, 191, 31))
        self.outputImageLabel_2.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.outputImageLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.outputImageLabel_2.setObjectName("outputImageLabel_2")
        self.inputImageLabel_2 = QtWidgets.QLabel(self.ImagesFrame_2)
        self.inputImageLabel_2.setGeometry(QtCore.QRect(170, 10, 191, 31))
        self.inputImageLabel_2.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.inputImageLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.inputImageLabel_2.setObjectName("inputImageLabel_2")
        self.EdgeDetection_inputImage = QtWidgets.QLabel(self.ImagesFrame_2)
        self.EdgeDetection_inputImage.setGeometry(QtCore.QRect(20, 50, 512, 512))
        self.EdgeDetection_inputImage.setStyleSheet("border: 4px solid black;\n"
"")
        self.EdgeDetection_inputImage.setText("")
        self.EdgeDetection_inputImage.setScaledContents(True)
        self.EdgeDetection_inputImage.setAlignment(QtCore.Qt.AlignCenter)
        self.EdgeDetection_inputImage.setObjectName("EdgeDetection_inputImage")
        self.EdgeDetection_outputImage = QtWidgets.QLabel(self.ImagesFrame_2)
        self.EdgeDetection_outputImage.setGeometry(QtCore.QRect(580, 50, 512, 512))
        self.EdgeDetection_outputImage.setStyleSheet("border: 4px solid black;\n"
"")
        self.EdgeDetection_outputImage.setText("")
        self.EdgeDetection_outputImage.setScaledContents(True)
        self.EdgeDetection_outputImage.setAlignment(QtCore.Qt.AlignCenter)
        self.EdgeDetection_outputImage.setObjectName("EdgeDetection_outputImage")
        self.Prewitt = QtWidgets.QWidget(self.EdgeDetection)
        self.Prewitt.setGeometry(QtCore.QRect(20, 100, 251, 111))
        self.Prewitt.setStyleSheet("border: 2px solid;\n"
"border-radius: 5px;")
        self.Prewitt.setObjectName("Prewitt")
        self.PrewittButton = QtWidgets.QPushButton(self.Prewitt)
        self.PrewittButton.setGeometry(QtCore.QRect(20, 50, 211, 51))
        self.PrewittButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.PrewittButton.setObjectName("PrewittButton")
        self.label = QtWidgets.QLabel(self.Prewitt)
        self.label.setGeometry(QtCore.QRect(0, 10, 241, 31))
        self.label.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Robert = QtWidgets.QWidget(self.EdgeDetection)
        self.Robert.setGeometry(QtCore.QRect(20, 220, 251, 121))
        self.Robert.setStyleSheet("border: 2px solid;\n"
"border-radius: 5px;")
        self.Robert.setObjectName("Robert")
        self.label_2 = QtWidgets.QLabel(self.Robert)
        self.label_2.setGeometry(QtCore.QRect(0, 10, 241, 31))
        self.label_2.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.RobetButton = QtWidgets.QPushButton(self.Robert)
        self.RobetButton.setGeometry(QtCore.QRect(20, 50, 211, 51))
        self.RobetButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.RobetButton.setObjectName("RobetButton")
        self.Sobel = QtWidgets.QWidget(self.EdgeDetection)
        self.Sobel.setGeometry(QtCore.QRect(20, 360, 251, 121))
        self.Sobel.setStyleSheet("border: 2px solid;\n"
"border-radius: 5px;")
        self.Sobel.setObjectName("Sobel")
        self.label_3 = QtWidgets.QLabel(self.Sobel)
        self.label_3.setGeometry(QtCore.QRect(0, 10, 241, 31))
        self.label_3.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.SobelButton = QtWidgets.QPushButton(self.Sobel)
        self.SobelButton.setGeometry(QtCore.QRect(20, 50, 211, 51))
        self.SobelButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.SobelButton.setObjectName("SobelButton")
        self.Canny = QtWidgets.QWidget(self.EdgeDetection)
        self.Canny.setGeometry(QtCore.QRect(20, 490, 251, 121))
        self.Canny.setStyleSheet("border: 2px solid;\n"
"border-radius: 5px;")
        self.Canny.setObjectName("Canny")
        self.label_4 = QtWidgets.QLabel(self.Canny)
        self.label_4.setGeometry(QtCore.QRect(0, 10, 241, 31))
        self.label_4.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.CannyButton = QtWidgets.QPushButton(self.Canny)
        self.CannyButton.setGeometry(QtCore.QRect(20, 50, 211, 51))
        self.CannyButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.CannyButton.setObjectName("CannyButton")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/edge_detection.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.EdgeDetection, icon3, "")
        self.ThresholdTab = QtWidgets.QWidget()
        self.ThresholdTab.setObjectName("ThresholdTab")
        self.ImagesFrame_3 = QtWidgets.QFrame(self.ThresholdTab)
        self.ImagesFrame_3.setGeometry(QtCore.QRect(280, 50, 1121, 571))
        self.ImagesFrame_3.setStyleSheet("background-color: transparent;\n"
"border-radius:5px;")
        self.ImagesFrame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ImagesFrame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ImagesFrame_3.setObjectName("ImagesFrame_3")
        self.outputImageLabel_3 = QtWidgets.QLabel(self.ImagesFrame_3)
        self.outputImageLabel_3.setGeometry(QtCore.QRect(750, 10, 191, 31))
        self.outputImageLabel_3.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.outputImageLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.outputImageLabel_3.setObjectName("outputImageLabel_3")
        self.inputImageLabel_3 = QtWidgets.QLabel(self.ImagesFrame_3)
        self.inputImageLabel_3.setGeometry(QtCore.QRect(170, 10, 191, 31))
        self.inputImageLabel_3.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.inputImageLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.inputImageLabel_3.setObjectName("inputImageLabel_3")
        self.Threshold_InputImage = QtWidgets.QLabel(self.ImagesFrame_3)
        self.Threshold_InputImage.setGeometry(QtCore.QRect(20, 50, 512, 512))
        self.Threshold_InputImage.setStyleSheet("border: 4px solid black;\n"
"")
        self.Threshold_InputImage.setText("")
        self.Threshold_InputImage.setScaledContents(True)
        self.Threshold_InputImage.setAlignment(QtCore.Qt.AlignCenter)
        self.Threshold_InputImage.setObjectName("Threshold_InputImage")
        self.Threshold_OutputImage = QtWidgets.QLabel(self.ImagesFrame_3)
        self.Threshold_OutputImage.setGeometry(QtCore.QRect(580, 50, 512, 512))
        self.Threshold_OutputImage.setStyleSheet("border: 4px solid black;\n"
"")
        self.Threshold_OutputImage.setText("")
        self.Threshold_OutputImage.setScaledContents(True)
        self.Threshold_OutputImage.setAlignment(QtCore.Qt.AlignCenter)
        self.Threshold_OutputImage.setObjectName("Threshold_OutputImage")
        self.GlobalThresholdSlider = QtWidgets.QSlider(self.ImagesFrame_3)
        self.GlobalThresholdSlider.setGeometry(QtCore.QRect(590, 70, 16, 131))
        self.GlobalThresholdSlider.setMaximum(255)
        self.GlobalThresholdSlider.setOrientation(QtCore.Qt.Vertical)
        self.GlobalThresholdSlider.setObjectName("GlobalThresholdSlider")
        self.LocalThershold = QtWidgets.QWidget(self.ThresholdTab)
        self.LocalThershold.setGeometry(QtCore.QRect(30, 100, 241, 121))
        self.LocalThershold.setStyleSheet("border: 2px solid;\n"
"border-radius: 5px;")
        self.LocalThershold.setObjectName("LocalThershold")
        self.LocalThresholdButton = QtWidgets.QPushButton(self.LocalThershold)
        self.LocalThresholdButton.setGeometry(QtCore.QRect(50, 50, 151, 51))
        self.LocalThresholdButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.LocalThresholdButton.setObjectName("LocalThresholdButton")
        self.LocalLabel = QtWidgets.QLabel(self.LocalThershold)
        self.LocalLabel.setGeometry(QtCore.QRect(0, 10, 241, 31))
        self.LocalLabel.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.LocalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LocalLabel.setObjectName("LocalLabel")
        self.GlobalThreshold = QtWidgets.QWidget(self.ThresholdTab)
        self.GlobalThreshold.setGeometry(QtCore.QRect(30, 230, 241, 121))
        self.GlobalThreshold.setStyleSheet("border: 2px solid;\n"
"border-radius: 5px;")
        self.GlobalThreshold.setObjectName("GlobalThreshold")
        self.GlobalThresholdButton = QtWidgets.QPushButton(self.GlobalThreshold)
        self.GlobalThresholdButton.setGeometry(QtCore.QRect(50, 50, 151, 51))
        self.GlobalThresholdButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.GlobalThresholdButton.setObjectName("GlobalThresholdButton")
        self.GlobalLabel = QtWidgets.QLabel(self.GlobalThreshold)
        self.GlobalLabel.setGeometry(QtCore.QRect(0, 10, 241, 31))
        self.GlobalLabel.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.GlobalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.GlobalLabel.setObjectName("GlobalLabel")
        self.Normalize = QtWidgets.QWidget(self.ThresholdTab)
        self.Normalize.setGeometry(QtCore.QRect(30, 360, 241, 121))
        self.Normalize.setStyleSheet("border: 2px solid;\n"
"border-radius: 5px;")
        self.Normalize.setObjectName("Normalize")
        self.NormalizeButton = QtWidgets.QPushButton(self.Normalize)
        self.NormalizeButton.setGeometry(QtCore.QRect(50, 50, 151, 51))
        self.NormalizeButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.NormalizeButton.setObjectName("NormalizeButton")
        self.NormalizeLabel = QtWidgets.QLabel(self.Normalize)
        self.NormalizeLabel.setGeometry(QtCore.QRect(0, 10, 241, 31))
        self.NormalizeLabel.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.NormalizeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NormalizeLabel.setObjectName("NormalizeLabel")
        self.Equalize = QtWidgets.QWidget(self.ThresholdTab)
        self.Equalize.setGeometry(QtCore.QRect(30, 490, 241, 121))
        self.Equalize.setStyleSheet("border: 2px solid;\n"
"border-radius: 5px;")
        self.Equalize.setObjectName("Equalize")
        self.EqualizeButton = QtWidgets.QPushButton(self.Equalize)
        self.EqualizeButton.setGeometry(QtCore.QRect(50, 50, 151, 51))
        self.EqualizeButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.EqualizeButton.setObjectName("EqualizeButton")
        self.EqualizeLabel = QtWidgets.QLabel(self.Equalize)
        self.EqualizeLabel.setGeometry(QtCore.QRect(0, 10, 241, 31))
        self.EqualizeLabel.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.EqualizeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.EqualizeLabel.setObjectName("EqualizeLabel")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Threshold.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.ThresholdTab, icon4, "")
        self.Frequency = QtWidgets.QWidget()
        self.Frequency.setObjectName("Frequency")
        self.hybridInputImage1 = QtWidgets.QLabel(self.Frequency)
        self.hybridInputImage1.setGeometry(QtCore.QRect(60, 60, 256, 256))
        self.hybridInputImage1.setStyleSheet("border: 4px solid black;\n"
"")
        self.hybridInputImage1.setText("")
        self.hybridInputImage1.setScaledContents(True)
        self.hybridInputImage1.setAlignment(QtCore.Qt.AlignCenter)
        self.hybridInputImage1.setObjectName("hybridInputImage1")
        self.freqOutputImage1 = QtWidgets.QLabel(self.Frequency)
        self.freqOutputImage1.setGeometry(QtCore.QRect(410, 60, 256, 256))
        self.freqOutputImage1.setStyleSheet("border: 4px solid black;\n"
"")
        self.freqOutputImage1.setText("")
        self.freqOutputImage1.setScaledContents(True)
        self.freqOutputImage1.setAlignment(QtCore.Qt.AlignCenter)
        self.freqOutputImage1.setObjectName("freqOutputImage1")
        self.hybridInputImage2 = QtWidgets.QLabel(self.Frequency)
        self.hybridInputImage2.setGeometry(QtCore.QRect(60, 350, 256, 256))
        self.hybridInputImage2.setStyleSheet("border: 4px solid black;\n"
"")
        self.hybridInputImage2.setText("")
        self.hybridInputImage2.setScaledContents(True)
        self.hybridInputImage2.setAlignment(QtCore.Qt.AlignCenter)
        self.hybridInputImage2.setObjectName("hybridInputImage2")
        self.freqOutputImage2 = QtWidgets.QLabel(self.Frequency)
        self.freqOutputImage2.setGeometry(QtCore.QRect(410, 350, 256, 256))
        self.freqOutputImage2.setStyleSheet("border: 4px solid black;\n"
"")
        self.freqOutputImage2.setText("")
        self.freqOutputImage2.setScaledContents(True)
        self.freqOutputImage2.setAlignment(QtCore.Qt.AlignCenter)
        self.freqOutputImage2.setObjectName("freqOutputImage2")
        self.Image1FSlider = QtWidgets.QSlider(self.Frequency)
        self.Image1FSlider.setGeometry(QtCore.QRect(350, 140, 16, 45))
        self.Image1FSlider.setMaximum(1)
        self.Image1FSlider.setPageStep(10)
        self.Image1FSlider.setSliderPosition(1)
        self.Image1FSlider.setOrientation(QtCore.Qt.Vertical)
        self.Image1FSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.Image1FSlider.setTickInterval(0)
        self.Image1FSlider.setObjectName("Image1FSlider")
        self.Image2FSlider = QtWidgets.QSlider(self.Frequency)
        self.Image2FSlider.setGeometry(QtCore.QRect(350, 440, 16, 45))
        self.Image2FSlider.setMaximum(1)
        self.Image2FSlider.setPageStep(10)
        self.Image2FSlider.setSliderPosition(0)
        self.Image2FSlider.setOrientation(QtCore.Qt.Vertical)
        self.Image2FSlider.setInvertedAppearance(False)
        self.Image2FSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.Image2FSlider.setObjectName("Image2FSlider")
        self.UploadeImage1 = QtWidgets.QPushButton(self.Frequency)
        self.UploadeImage1.setGeometry(QtCore.QRect(330, 50, 61, 61))
        self.UploadeImage1.setStyleSheet("QPushButton{\n"
"border-radius: 25px;\n"
"font: 900 12pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.UploadeImage1.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/UploadIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UploadeImage1.setIcon(icon5)
        self.UploadeImage1.setIconSize(QtCore.QSize(60, 60))
        self.UploadeImage1.setObjectName("UploadeImage1")
        self.UploadeImage2 = QtWidgets.QPushButton(self.Frequency)
        self.UploadeImage2.setGeometry(QtCore.QRect(330, 350, 61, 61))
        self.UploadeImage2.setStyleSheet("QPushButton{\n"
"border-radius: 25px;\n"
"font: 900 12pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.UploadeImage2.setText("")
        self.UploadeImage2.setIcon(icon5)
        self.UploadeImage2.setIconSize(QtCore.QSize(60, 60))
        self.UploadeImage2.setObjectName("UploadeImage2")
        self.finalHybridImage = QtWidgets.QLabel(self.Frequency)
        self.finalHybridImage.setGeometry(QtCore.QRect(820, 60, 512, 545))
        self.finalHybridImage.setStyleSheet("border: 4px solid black;\n"
"")
        self.finalHybridImage.setText("")
        self.finalHybridImage.setScaledContents(True)
        self.finalHybridImage.setAlignment(QtCore.Qt.AlignCenter)
        self.finalHybridImage.setObjectName("finalHybridImage")
        self.HybridButton = QtWidgets.QPushButton(self.Frequency)
        self.HybridButton.setGeometry(QtCore.QRect(710, 310, 61, 61))
        self.HybridButton.setStyleSheet("QPushButton{\n"
"border-radius: 25px;\n"
"font: 900 12pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.HybridButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/hybrid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.HybridButton.setIcon(icon6)
        self.HybridButton.setIconSize(QtCore.QSize(60, 60))
        self.HybridButton.setObjectName("HybridButton")
        self.freqOutputImage2Slider = QtWidgets.QSlider(self.Frequency)
        self.freqOutputImage2Slider.setGeometry(QtCore.QRect(350, 530, 16, 70))
        self.freqOutputImage2Slider.setMaximum(255)
        self.freqOutputImage2Slider.setOrientation(QtCore.Qt.Vertical)
        self.freqOutputImage2Slider.setObjectName("freqOutputImage2Slider")
        self.freqOutputImage1Slider = QtWidgets.QSlider(self.Frequency)
        self.freqOutputImage1Slider.setGeometry(QtCore.QRect(350, 230, 16, 70))
        self.freqOutputImage1Slider.setOrientation(QtCore.Qt.Vertical)
        self.freqOutputImage1Slider.setObjectName("freqOutputImage1Slider")
        self.label_5 = QtWidgets.QLabel(self.Frequency)
        self.label_5.setGeometry(QtCore.QRect(350, 110, 16, 31))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.Frequency)
        self.label_6.setGeometry(QtCore.QRect(350, 180, 16, 31))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.Frequency)
        self.label_7.setGeometry(QtCore.QRect(350, 410, 16, 31))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.Frequency)
        self.label_8.setGeometry(QtCore.QRect(350, 480, 16, 31))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.Frequency)
        self.label_9.setGeometry(QtCore.QRect(360, 510, 31, 31))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.Frequency)
        self.label_10.setGeometry(QtCore.QRect(360, 580, 31, 31))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.Frequency)
        self.label_11.setGeometry(QtCore.QRect(360, 280, 31, 31))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.Frequency)
        self.label_12.setGeometry(QtCore.QRect(360, 210, 31, 31))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.inputImageLabel_4 = QtWidgets.QLabel(self.Frequency)
        self.inputImageLabel_4.setGeometry(QtCore.QRect(90, 30, 191, 31))
        self.inputImageLabel_4.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color:transparent;")
        self.inputImageLabel_4.setAlignment(QtCore.Qt.AlignCenter)
        self.inputImageLabel_4.setObjectName("inputImageLabel_4")
        self.inputImageLabel_5 = QtWidgets.QLabel(self.Frequency)
        self.inputImageLabel_5.setGeometry(QtCore.QRect(90, 320, 191, 31))
        self.inputImageLabel_5.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color:transparent;")
        self.inputImageLabel_5.setAlignment(QtCore.Qt.AlignCenter)
        self.inputImageLabel_5.setObjectName("inputImageLabel_5")
        self.tabWidget.addTab(self.Frequency, icon6, "")
        self.BrowseButton = QtWidgets.QPushButton(self.centralwidget)
        self.BrowseButton.setGeometry(QtCore.QRect(1120, 0, 181, 61))
        self.BrowseButton.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"text-align: left;\n"
"font: 900 12pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"")
        self.BrowseButton.setIcon(icon5)
        self.BrowseButton.setIconSize(QtCore.QSize(50, 50))
        self.BrowseButton.setObjectName("BrowseButton")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1300, 0, 71, 61))
        self.pushButton.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"font: 900 12pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.pushButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon7)
        self.pushButton.setIconSize(QtCore.QSize(25, 25))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.outputImageLabel.setText(_translate("MainWindow", "Output "))
        self.inputImageLabel.setText(_translate("MainWindow", "Input"))
        self.AverageFilterButton.setText(_translate("MainWindow", "Average Filter"))
        self.MedianFilterButton.setText(_translate("MainWindow", "Median Filter"))
        self.GaussianFilterButton.setText(_translate("MainWindow", "Gaussian Filter"))
        self.Radio3x3Kernal.setText(_translate("MainWindow", "3x3"))
        self.Radio5x5Kernal.setText(_translate("MainWindow", "5x5"))
        self.UniformNoiseButton.setText(_translate("MainWindow", "Uniform Noise"))
        self.SaltPepperNoiseButton.setText(_translate("MainWindow", "Salt and Pepper Noise"))
        self.GaussianNoiseButton.setText(_translate("MainWindow", "Gaussian Noise"))
        self.FilterLabel.setText(_translate("MainWindow", "Filter Types"))
        self.NoiseLabel.setText(_translate("MainWindow", "Noise Types"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.FilterTab), _translate("MainWindow", "Filter"))
        self.A6.setText(_translate("MainWindow", "DF"))
        self.A5.setText(_translate("MainWindow", " CDF"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.HistogramTab), _translate("MainWindow", "Histogram"))
        self.outputImageLabel_2.setText(_translate("MainWindow", "Output "))
        self.inputImageLabel_2.setText(_translate("MainWindow", "Input"))
        self.PrewittButton.setText(_translate("MainWindow", "Prewitt Edge Technique"))
        self.label.setText(_translate("MainWindow", "Prewitt"))
        self.label_2.setText(_translate("MainWindow", "Robert"))
        self.RobetButton.setText(_translate("MainWindow", "Robert Edge Technique"))
        self.label_3.setText(_translate("MainWindow", "Sobel"))
        self.SobelButton.setText(_translate("MainWindow", "Sobel Edge Technique"))
        self.label_4.setText(_translate("MainWindow", "Canny"))
        self.CannyButton.setText(_translate("MainWindow", "Canny Edge Technique"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.EdgeDetection), _translate("MainWindow", "Edge Detection"))
        self.outputImageLabel_3.setText(_translate("MainWindow", "Output "))
        self.inputImageLabel_3.setText(_translate("MainWindow", "Input"))
        self.LocalThresholdButton.setText(_translate("MainWindow", "Apply"))
        self.LocalLabel.setText(_translate("MainWindow", "Local Threshold"))
        self.GlobalThresholdButton.setText(_translate("MainWindow", "Apply"))
        self.GlobalLabel.setText(_translate("MainWindow", "Global Threshold"))
        self.NormalizeButton.setText(_translate("MainWindow", "Apply"))
        self.NormalizeLabel.setText(_translate("MainWindow", "Normalize"))
        self.EqualizeButton.setText(_translate("MainWindow", "Apply"))
        self.EqualizeLabel.setText(_translate("MainWindow", "Equalize"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ThresholdTab), _translate("MainWindow", "Threshold"))
        self.label_5.setText(_translate("MainWindow", "H"))
        self.label_6.setText(_translate("MainWindow", "L"))
        self.label_7.setText(_translate("MainWindow", "H"))
        self.label_8.setText(_translate("MainWindow", "L"))
        self.label_9.setText(_translate("MainWindow", "255"))
        self.label_10.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "0"))
        self.label_12.setText(_translate("MainWindow", "255"))
        self.inputImageLabel_4.setText(_translate("MainWindow", "Image 1"))
        self.inputImageLabel_5.setText(_translate("MainWindow", "Image 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Frequency), _translate("MainWindow", "Hybrid"))
        self.BrowseButton.setText(_translate("MainWindow", "Upload Image"))
